
export const catsData = [
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "https://th.bing.com/th?id=OIP.VWOCLsrBU_cdmbzFkIPbsQHaE8&w=306&h=204&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody", "insomniac"],
        isGif: false,
        image: "https://th.bing.com/th/id/OIP.LL_EptMbU6Z6xFOa7wgG3AHaFj?w=215&h=180&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "https://th.bing.com/th/id/OIP.ingBmkSlZ1WapJd6Wbm89QHaFj?w=249&h=187&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["confused", "sad"],
        isGif: false,
        image: "https://th.bing.com/th/id/OIP.kGqYV_IxpYqATaSYlm1EegHaHa?w=191&h=191&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking confused",
    },
    {
        emotionTags: ["dominant", "moody"],
        isGif: false,
        image: "https://th.bing.com/th/id/OIP.O21O10UUMdtcI_BsMbZQ_wHaHv?rs=1&pid=ImgDetMain",
        alt: "A cat looking dominant",
    },
    {
        emotionTags: ["happy", "relaxed"],
        isGif: false,
        image: "https://www.bing.com/th?id=OIP.navHWS2VU-tiGs-AZizmgAHaFj&w=143&h=106&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2",
        alt: "A cat looking happy",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "https://www.bing.com/th?id=OIP.tUIcHBPGUUwIU-t6hQ3idgHaE8&w=169&h=106&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "https://www.bing.com/th?id=OIP.tUIcHBPGUUwIU-t6hQ3idgHaE8&w=169&h=106&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "https://th.bing.com/th/id/OIP.iueFMAzwtkELlHu9EpCC5gHaFj?w=229&h=180&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "https://th.bing.com/th?id=OIP.ingBmkSlZ1WapJd6Wbm89QHaFj&w=288&h=216&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["relaxed"],
        isGif: false,
        image: "https://www.bing.com/th?id=OIP.z8hZD8yP9Y4eA-S5UWUH6wHaE8&w=169&h=106&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2",
        alt: "A cat looking lazy",
    },
    {
        emotionTags: ["scared"],
        isGif: false,
        image: "https://th.bing.com/th/id/OIP.iueFMAzwtkELlHu9EpCC5gHaFj?w=229&h=180&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking nervous",
    },
    {
        emotionTags: ["sad"],
        isGif: false,
        image: "https://www.bing.com/th?id=OIP.24LwgSvaeWFp53oNtYjvpwHaGp&w=116&h=104&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2",
        alt: "A cat looking sad",
    },
    {
        emotionTags: ["sad", "moody"],
        isGif: false,
        image: "https://th.bing.com/th/id/OIP.kGqYV_IxpYqATaSYlm1EegHaHa?w=191&h=191&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking sad",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.ingBmkSlZ1WapJd6Wbm89QHaFj?w=249&h=187&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking moody",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.ingBmkSlZ1WapJd6Wbm89QHaFj?w=249&h=187&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking angry",
    },
    {
        emotionTags: ["confused"],
        isGif: true,
        image: "https://th.bing.com/th?id=OIP.9o6yy_4lDNGDlcaVD1DSoQHaHa&w=250&h=250&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2",
        alt: "A cat looking confused",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.O21O10UUMdtcI_BsMbZQ_wHaHv?rs=1&pid=ImgDetMain",
        alt: "A cat looking dominant",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "https://www.bing.com/th?id=OIP.navHWS2VU-tiGs-AZizmgAHaFj&w=143&h=106&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2",
        alt: "A cat looking happy",
    },
    {
        emotionTags: ["hungry", "sad", "confused"],
        isGif: true,
        image: "https://th.bing.com/th?id=OIP.9o6yy_4lDNGDlcaVD1DSoQHaHa&w=250&h=250&c=8&rs=1&qlt=90&o=6&dpr=1.1&pid=3.1&rm=2",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.TeUgLRblDypB1iqsmWRR6wHaE8?w=255&h=180&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.TeUgLRblDypB1iqsmWRR6wHaE8?w=255&h=180&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking hungry",
    },
    {
        emotionTags: ["insomniac", "scared"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.iueFMAzwtkELlHu9EpCC5gHaFj?w=229&h=180&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking insomniac",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.A9ly6XU5hvVg7uQKxKqQ5wHaEo?w=299&h=186&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking relaxed",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.A9ly6XU5hvVg7uQKxKqQ5wHaEo?w=299&h=186&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking relaxed",
    },
    {
        emotionTags: ["scared", "sad"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.kGqYV_IxpYqATaSYlm1EegHaHa?w=191&h=191&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking nervous",
    },
    {
        emotionTags: ["scared"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.iueFMAzwtkELlHu9EpCC5gHaFj?w=229&h=180&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking scared",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "https://th.bing.com/th/id/OIP.kGqYV_IxpYqATaSYlm1EegHaHa?w=191&h=191&c=7&r=0&o=5&dpr=1.1&pid=1.7",
        alt: "A cat looking sad",
    },
]

